services:
  elasticsearch:
    image: elasticsearch:8.11.3
    network_mode: host
    #    ports:
    #      - 9200:9200
    environment:
      - node.name=es01
      - ELASTIC_PASSWORD=elastic
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.watermark.low=5gb
      - cluster.routing.allocation.disk.watermark.high=3gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
    mem_limit: 8g
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - esdata01:/data/elasticsearch/data
    restart: on-failure

volumes:
  esdata01:
    driver: local
